// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class FinCostDetail
    {
        public int Id { get; set; }
        public int CostId { get; set; }
        public decimal Amount { get; set; }
        public byte CostCenterId { get; set; }
        public byte CostItemId { get; set; }
        public string Description { get; set; }

        public virtual FinCost Cost { get; set; }
        public virtual FinCostCenter CostCenter { get; set; }
        public virtual FinCostItem CostItem { get; set; }
    }
}