// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class FinCostItem
    {
        public FinCostItem()
        {
            FinCostDetails = new HashSet<FinCostDetail>();
        }

        public byte Id { get; set; }
        public string Name { get; set; }
        public byte StatusId { get; set; }

        public virtual ICollection<FinCostDetail> FinCostDetails { get; set; }
    }
}