// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class FinProjectSupplyOrder
    {
        public FinProjectSupplyOrder()
        {
            FinSupplyOrderAttachments = new HashSet<FinSupplyOrderAttachment>();
            FinSupplyOrderInvoices = new HashSet<FinSupplyOrderInvoice>();
        }

        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int Code { get; set; }
        public int MainContractorSupplyOrderNo { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }
        public decimal AddedValue { get; set; }
        public byte StatusId { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifyDate { get; set; }

        public virtual SecUser CreatedByNavigation { get; set; }
        public virtual LtCurrency Currency { get; set; }
        public virtual SecUser ModifiedByNavigation { get; set; }
        public virtual PmProject Project { get; set; }
        public virtual LtStatus Status { get; set; }
        public virtual ICollection<FinSupplyOrderAttachment> FinSupplyOrderAttachments { get; set; }
        public virtual ICollection<FinSupplyOrderInvoice> FinSupplyOrderInvoices { get; set; }
    }
}