// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class FinSupplyOrderAttachment
    {
        public int Id { get; set; }
        public int SupplyOrderId { get; set; }
        public string Filename { get; set; }
        public string Title { get; set; }
        public byte? DocTypeId { get; set; }
        public int UploadedBy { get; set; }
        public DateTime UploadDate { get; set; }

        public virtual LtDocType DocType { get; set; }
        public virtual FinProjectSupplyOrder SupplyOrder { get; set; }
        public virtual SecUser UploadedByNavigation { get; set; }
    }
}