// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class FinSupplyOrderInvoice
    {
        public FinSupplyOrderInvoice()
        {
            FinInvoiceAttachments = new HashSet<FinInvoiceAttachment>();
        }

        public int Id { get; set; }
        public int SupplyOrderId { get; set; }
        public int Code { get; set; }
        public decimal Amount { get; set; }
        public string ElectronicInvoiceReference { get; set; }
        public DateTime ElectronicInvoiceDate { get; set; }
        public byte InvoiceStatusId { get; set; }
        public byte CollectionStatusId { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifyDate { get; set; }

        public virtual LtCollectionStatus CollectionStatus { get; set; }
        public virtual SecUser CreatedByNavigation { get; set; }
        public virtual LtInvoiceStatus InvoiceStatus { get; set; }
        public virtual SecUser ModifiedByNavigation { get; set; }
        public virtual FinProjectSupplyOrder SupplyOrder { get; set; }
        public virtual ICollection<FinInvoiceAttachment> FinInvoiceAttachments { get; set; }
    }
}