// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class LtCountry
    {
        public LtCountry()
        {
            LtCurrencies = new HashSet<LtCurrency>();
            LtGovernorates = new HashSet<LtGovernorate>();
            SecContactAddresses = new HashSet<SecContactAddress>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<LtCurrency> LtCurrencies { get; set; }
        public virtual ICollection<LtGovernorate> LtGovernorates { get; set; }
        public virtual ICollection<SecContactAddress> SecContactAddresses { get; set; }
    }
}