// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class LtCurrency
    {
        public LtCurrency()
        {
            FinCosts = new HashSet<FinCost>();
            FinProjectSupplyOrders = new HashSet<FinProjectSupplyOrder>();
        }

        public int Id { get; set; }
        public int CountryId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal ConversionRate { get; set; }
        public bool IsDefault { get; set; }

        public virtual LtCountry Country { get; set; }
        public virtual ICollection<FinCost> FinCosts { get; set; }
        public virtual ICollection<FinProjectSupplyOrder> FinProjectSupplyOrders { get; set; }
    }
}