// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class LtGovernorate
    {
        public LtGovernorate()
        {
            LtCities = new HashSet<LtCity>();
            SecContactAddresses = new HashSet<SecContactAddress>();
        }

        public int Id { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }

        public virtual LtCountry Country { get; set; }
        public virtual ICollection<LtCity> LtCities { get; set; }
        public virtual ICollection<SecContactAddress> SecContactAddresses { get; set; }
    }
}