// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using OneTrack.PM.Entities.Models.DB;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class OneTrackPMContext
    {
        private IOneTrackPMContextProcedures _procedures;

        public virtual IOneTrackPMContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new OneTrackPMContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public object ProjectPlan { get; set; }
        //public object ProjectPlans { get; set; }

        public IOneTrackPMContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SP_SEC_SelectUserPermissionResult>().HasNoKey().ToView(null);
        }
    }

    public partial class OneTrackPMContextProcedures : IOneTrackPMContextProcedures
    {
        private readonly OneTrackPMContext _context;

        public OneTrackPMContextProcedures(OneTrackPMContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_SEC_SelectUserPermissionResult>> SP_SEC_SelectUserPermissionAsync(int? UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UserId",
                    Value = UserId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_SEC_SelectUserPermissionResult>("EXEC @returnValue = [dbo].[SP_SEC_SelectUserPermission] @UserId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
