// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class PmProject
    {
        public PmProject()
        {
            FinCosts = new HashSet<FinCost>();
            FinProjectSupplyOrders = new HashSet<FinProjectSupplyOrder>();
            PmProjectAttachments = new HashSet<PmProjectAttachment>();
            PmStandardTasks = new HashSet<PmStandardTask>();
            SecMainModules = new HashSet<SecMainModule>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int MainContractorId { get; set; }
        public int ClientId { get; set; }
        public int IntermediaryContractorId { get; set; }
        public string MainContractorReference { get; set; }
        public string Description { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? ActualEndDate { get; set; }
        public byte StatusId { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifyDate { get; set; }

        public virtual SecContact Client { get; set; }
        public virtual SecUser CreatedByNavigation { get; set; }
        public virtual SecContact IntermediaryContractor { get; set; }
        public virtual SecContact MainContractor { get; set; }
        public virtual SecUser ModifiedByNavigation { get; set; }
        public virtual LtStatus Status { get; set; }
        public virtual ICollection<FinCost> FinCosts { get; set; }
        public virtual ICollection<FinProjectSupplyOrder> FinProjectSupplyOrders { get; set; }
        public virtual ICollection<PmProjectAttachment> PmProjectAttachments { get; set; }
        public virtual ICollection<PmStandardTask> PmStandardTasks { get; set; }
        public virtual ICollection<SecMainModule> SecMainModules { get; set; }
    }
}