// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class PmProjectPlan
    {
        public PmProjectPlan()
        {
            PmProjectPlanAttachments = new HashSet<PmProjectPlanAttachment>();
        }

        public int Id { get; set; }
        public int StandardTaskId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public decimal Progress { get; set; }

        public virtual PmStandardTask StandardTask { get; set; }
        public virtual ICollection<PmProjectPlanAttachment> PmProjectPlanAttachments { get; set; }
    }
}