// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecContactAddress
    {
        public int Id { get; set; }
        public int ContactId { get; set; }
        public string Street { get; set; }
        public string BuildingNo { get; set; }
        public string Address { get; set; }
        public string NearestHallmark { get; set; }
        public string Phone { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool? IsHomeAddress { get; set; }
        public int? CountryId { get; set; }
        public int? GovernorateId { get; set; }
        public int? CityId { get; set; }

        public virtual LtCity City { get; set; }
        public virtual SecContact Contact { get; set; }
        public virtual LtCountry Country { get; set; }
        public virtual LtGovernorate Governorate { get; set; }
    }
}