// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecContact
    {
        public SecContact()
        {
            FinCosts = new HashSet<FinCost>();
            PmProjectClients = new HashSet<PmProject>();
            PmProjectIntermediaryContractors = new HashSet<PmProject>();
            PmProjectMainContractors = new HashSet<PmProject>();
            SecContactAddresses = new HashSet<SecContactAddress>();
            SecContactImages = new HashSet<SecContactImage>();
            SecContactJobTitleContacts = new HashSet<SecContactJobTitle>();
            SecContactJobTitleEntities = new HashSet<SecContactJobTitle>();
            SecContactPhones = new HashSet<SecContactPhone>();
            SecContactRolesLinks = new HashSet<SecContactRolesLink>();
            SecUsers = new HashSet<SecUser>();
        }

        public int Id { get; set; }
        public int Code { get; set; }
        public string Barcode { get; set; }
        public string FullName { get; set; }
        public string NormalizedFullName { get; set; }
        public byte ContactTypeId { get; set; }
        public byte? TitleId { get; set; }
        public byte? GenderId { get; set; }
        public string Email { get; set; }
        public string NationalId { get; set; }
        public string Avatar { get; set; }
        public string Biography { get; set; }
        public byte StatusId { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual SecContactType ContactType { get; set; }
        public virtual SecContactGender Gender { get; set; }
        public virtual LtStatus Status { get; set; }
        public virtual SecTitle Title { get; set; }
        public virtual ICollection<FinCost> FinCosts { get; set; }
        public virtual ICollection<PmProject> PmProjectClients { get; set; }
        public virtual ICollection<PmProject> PmProjectIntermediaryContractors { get; set; }
        public virtual ICollection<PmProject> PmProjectMainContractors { get; set; }
        public virtual ICollection<SecContactAddress> SecContactAddresses { get; set; }
        public virtual ICollection<SecContactImage> SecContactImages { get; set; }
        public virtual ICollection<SecContactJobTitle> SecContactJobTitleContacts { get; set; }
        public virtual ICollection<SecContactJobTitle> SecContactJobTitleEntities { get; set; }
        public virtual ICollection<SecContactPhone> SecContactPhones { get; set; }
        public virtual ICollection<SecContactRolesLink> SecContactRolesLinks { get; set; }
        public virtual ICollection<SecUser> SecUsers { get; set; }
    }
}