// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecContactJobTitle
    {
        public int Id { get; set; }
        public int JobTitleId { get; set; }
        public int ContactId { get; set; }
        public int EntityId { get; set; }
        public bool IsActive { get; set; }

        public virtual SecContact Contact { get; set; }
        public virtual SecContact Entity { get; set; }
        public virtual SecJobTitle JobTitle { get; set; }
    }
}