// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecFormActionType
    {
        public SecFormActionType()
        {
            SecFormActionTypeAttachments = new HashSet<SecFormActionTypeAttachment>();
            SecGroupActions = new HashSet<SecGroupAction>();
        }

        public int Id { get; set; }
        public int FormId { get; set; }
        public byte ActionTypeId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }

        public virtual SecActionType ActionType { get; set; }
        public virtual SecModuleForm Form { get; set; }
        public virtual ICollection<SecFormActionTypeAttachment> SecFormActionTypeAttachments { get; set; }
        public virtual ICollection<SecGroupAction> SecGroupActions { get; set; }
    }
}