// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecGroupAction
    {
        public int Id { get; set; }
        public byte GroupId { get; set; }
        public int FormActionTypeId { get; set; }

        public virtual SecFormActionType FormActionType { get; set; }
        public virtual SecGroup Group { get; set; }
    }
}