// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecJobTitle
    {
        public SecJobTitle()
        {
            SecContactJobTitles = new HashSet<SecContactJobTitle>();
        }

        public int Id { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte StatusId { get; set; }

        public virtual LtStatus Status { get; set; }
        public virtual ICollection<SecContactJobTitle> SecContactJobTitles { get; set; }
    }
}