// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecModuleForm
    {
        public SecModuleForm()
        {
            SecFormActionTypes = new HashSet<SecFormActionType>();
            SecModuleFormAttachments = new HashSet<SecModuleFormAttachment>();
        }

        public int Id { get; set; }
        public int ModuleId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int? ParentId { get; set; }
        public int? OrderValue { get; set; }
        public string Description { get; set; }

        public virtual SecModule Module { get; set; }
        public virtual ICollection<SecFormActionType> SecFormActionTypes { get; set; }
        public virtual ICollection<SecModuleFormAttachment> SecModuleFormAttachments { get; set; }
    }
}