// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecModule
    {
        public SecModule()
        {
            SecModuleAttachments = new HashSet<SecModuleAttachment>();
            SecModuleForms = new HashSet<SecModuleForm>();
        }

        public int Id { get; set; }
        public int? MainModuleId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public byte? OrderValue { get; set; }
        public string Description { get; set; }

        public virtual SecMainModule MainModule { get; set; }
        public virtual ICollection<SecModuleAttachment> SecModuleAttachments { get; set; }
        public virtual ICollection<SecModuleForm> SecModuleForms { get; set; }
    }
}