// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecMainModule
    {
        public SecMainModule()
        {
            SecGroups = new HashSet<SecGroup>();
            SecMainModuleAttachments = new HashSet<SecMainModuleAttachment>();
            SecModules = new HashSet<SecModule>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int? ProjectId { get; set; }
        public string Description { get; set; }

        public virtual PmProject Project { get; set; }
        public virtual ICollection<SecGroup> SecGroups { get; set; }
        public virtual ICollection<SecMainModuleAttachment> SecMainModuleAttachments { get; set; }
        public virtual ICollection<SecModule> SecModules { get; set; }
    }
}