// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecTitle
    {
        public SecTitle()
        {
            SecContacts = new HashSet<SecContact>();
        }

        public byte Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SecContact> SecContacts { get; set; }
    }
}