// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SecUser
    {
        public SecUser()
        {
            FinCostAttachments = new HashSet<FinCostAttachment>();
            FinCostCreatedByNavigations = new HashSet<FinCost>();
            FinCostModifiedByNavigations = new HashSet<FinCost>();
            FinInvoiceAttachments = new HashSet<FinInvoiceAttachment>();
            FinProjectSupplyOrderCreatedByNavigations = new HashSet<FinProjectSupplyOrder>();
            FinProjectSupplyOrderModifiedByNavigations = new HashSet<FinProjectSupplyOrder>();
            FinSupplyOrderAttachments = new HashSet<FinSupplyOrderAttachment>();
            FinSupplyOrderInvoiceCreatedByNavigations = new HashSet<FinSupplyOrderInvoice>();
            FinSupplyOrderInvoiceModifiedByNavigations = new HashSet<FinSupplyOrderInvoice>();
            PmProjectAttachments = new HashSet<PmProjectAttachment>();
            PmProjectCreatedByNavigations = new HashSet<PmProject>();
            PmProjectModifiedByNavigations = new HashSet<PmProject>();
            PmProjectPlanAttachments = new HashSet<PmProjectPlanAttachment>();
            PmStandardTaskCreatedByNavigations = new HashSet<PmStandardTask>();
            PmStandardTaskModifiedByNavigations = new HashSet<PmStandardTask>();
            SecFormActionTypeAttachments = new HashSet<SecFormActionTypeAttachment>();
            SecMainModuleAttachments = new HashSet<SecMainModuleAttachment>();
            SecModuleAttachments = new HashSet<SecModuleAttachment>();
            SecModuleFormAttachments = new HashSet<SecModuleFormAttachment>();
            SecUsersLogins = new HashSet<SecUsersLogin>();
            SecUsersRefreshTokens = new HashSet<SecUsersRefreshToken>();
            SysExceptionLogs = new HashSet<SysExceptionLog>();
        }

        public int Id { get; set; }
        public int ContactId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public byte GroupId { get; set; }
        public bool? IsLocked { get; set; }
        public byte? NoOfLoginAttempts { get; set; }
        public byte StatusId { get; set; }

        public virtual SecContact Contact { get; set; }
        public virtual SecGroup Group { get; set; }
        public virtual LtStatus Status { get; set; }
        public virtual ICollection<FinCostAttachment> FinCostAttachments { get; set; }
        public virtual ICollection<FinCost> FinCostCreatedByNavigations { get; set; }
        public virtual ICollection<FinCost> FinCostModifiedByNavigations { get; set; }
        public virtual ICollection<FinInvoiceAttachment> FinInvoiceAttachments { get; set; }
        public virtual ICollection<FinProjectSupplyOrder> FinProjectSupplyOrderCreatedByNavigations { get; set; }
        public virtual ICollection<FinProjectSupplyOrder> FinProjectSupplyOrderModifiedByNavigations { get; set; }
        public virtual ICollection<FinSupplyOrderAttachment> FinSupplyOrderAttachments { get; set; }
        public virtual ICollection<FinSupplyOrderInvoice> FinSupplyOrderInvoiceCreatedByNavigations { get; set; }
        public virtual ICollection<FinSupplyOrderInvoice> FinSupplyOrderInvoiceModifiedByNavigations { get; set; }
        public virtual ICollection<PmProjectAttachment> PmProjectAttachments { get; set; }
        public virtual ICollection<PmProject> PmProjectCreatedByNavigations { get; set; }
        public virtual ICollection<PmProject> PmProjectModifiedByNavigations { get; set; }
        public virtual ICollection<PmProjectPlanAttachment> PmProjectPlanAttachments { get; set; }
        public virtual ICollection<PmStandardTask> PmStandardTaskCreatedByNavigations { get; set; }
        public virtual ICollection<PmStandardTask> PmStandardTaskModifiedByNavigations { get; set; }
        public virtual ICollection<SecFormActionTypeAttachment> SecFormActionTypeAttachments { get; set; }
        public virtual ICollection<SecMainModuleAttachment> SecMainModuleAttachments { get; set; }
        public virtual ICollection<SecModuleAttachment> SecModuleAttachments { get; set; }
        public virtual ICollection<SecModuleFormAttachment> SecModuleFormAttachments { get; set; }
        public virtual ICollection<SecUsersLogin> SecUsersLogins { get; set; }
        public virtual ICollection<SecUsersRefreshToken> SecUsersRefreshTokens { get; set; }
        public virtual ICollection<SysExceptionLog> SysExceptionLogs { get; set; }
    }
}