// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OneTrack.PM.Entities.Models.DB
{
    public partial class SP_SEC_SelectUserPermissionResult
    {
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string PageName { get; set; }
        public string Url { get; set; }
        public string ParentForm { get; set; }
        public string ParentUrl { get; set; }
        public bool? _Read { get; set; }
        public bool? _Create { get; set; }
        public bool? _Update { get; set; }
        public bool? _Delete { get; set; }
        public bool? _Export { get; set; }
        public bool? _Print { get; set; }
        public bool? _Approve { get; set; }
        public bool? _Freeze { get; set; }
    }
}
